from pathlib import Path

activity_path = Path('app/src/main/java/ru/evrasia/research/WebResearchV10Activity.kt')
activity = activity_path.read_text()

activity = activity.replace('    private lateinit var stats: TextView\n    private lateinit var statsPanel: LinearLayout\n    private lateinit var statsHeader: Button\n    private lateinit var bookmarkSpinner: Spinner\n    private lateinit var bookmarkAdapter: ArrayAdapter<String>\n', '    private lateinit var bookmarkSpinner: Spinner\n    private lateinit var navigationController: WebNavigationController\n    private lateinit var bookmarkController: WebBookmarkController\n    private lateinit var statsController: WebCookieStatsController\n')
activity = activity.replace('    private val bookmarks = mutableListOf<String>()\n', '')
activity = activity.replace('    private val statsHandler = Handler(Looper.getMainLooper())\n    private val statsTicker = object : Runnable {\n        override fun run() {\n            if (::statsPanel.isInitialized && statsPanel.visibility == View.VISIBLE) {\n                updateStats()\n                statsHandler.postDelayed(this, 500)\n            }\n        }\n    }\n', '    private val uiHandler = Handler(Looper.getMainLooper())\n')

activity = activity.replace('if (actionId == EditorInfo.IME_ACTION_GO) { navigate(text.toString()); true } else false', 'if (actionId == EditorInfo.IME_ACTION_GO) { navigationController.navigate(text.toString()); true } else false')
activity = activity.replace('val go = actionButton("→") { navigate(address.text.toString()) }', 'val go = actionButton("→") { navigationController.navigate(address.text.toString()) }')

old_bookmarks = '''        bookmarkSpinner = Spinner(this)\n        bookmarkAdapter = ArrayAdapter(this, android.R.layout.simple_spinner_dropdown_item, bookmarks)\n        bookmarkSpinner.adapter = bookmarkAdapter\n        val openBookmark = compactButton("Открыть") { if (bookmarks.isNotEmpty()) navigate(bookmarks[bookmarkSpinner.selectedItemPosition]) }\n        val saveBookmark = compactButton("★") { saveBookmark(address.text.toString()) }\n        val deleteBookmark = compactButton("−") { deleteSelectedBookmark() }\n        bookmarkRow.addView(bookmarkSpinner, LinearLayout.LayoutParams(0, dp(44), 1f))\n        bookmarkRow.addView(openBookmark)\n        bookmarkRow.addView(saveBookmark)\n        bookmarkRow.addView(deleteBookmark)\n        bookmarkCard.addView(bookmarkRow)\n        root.addView(bookmarkCard, LinearLayout.LayoutParams(-1, -2).apply { setMargins(dp(12), 0, dp(12), dp(8)) })\n        loadBookmarks()\n'''
new_bookmarks = '''        bookmarkSpinner = Spinner(this)\n        bookmarkController = WebBookmarkController(\n            activity = this,\n            normalizeUrl = { raw -> navigationController.normalizeUrl(raw) },\n            onOpen = { url -> navigationController.navigate(url) }\n        )\n        bookmarkController.bind(bookmarkSpinner)\n        val openBookmark = compactButton("Открыть") { bookmarkController.openSelected() }\n        val saveBookmark = compactButton("★") { bookmarkController.save(address.text.toString()) }\n        val deleteBookmark = compactButton("−") { bookmarkController.deleteSelected() }\n        bookmarkRow.addView(bookmarkSpinner, LinearLayout.LayoutParams(0, dp(44), 1f))\n        bookmarkRow.addView(openBookmark)\n        bookmarkRow.addView(saveBookmark)\n        bookmarkRow.addView(deleteBookmark)\n        bookmarkCard.addView(bookmarkRow)\n        root.addView(bookmarkCard, LinearLayout.LayoutParams(-1, -2).apply { setMargins(dp(12), 0, dp(12), dp(8)) })\n'''
if old_bookmarks not in activity:
    raise SystemExit('bookmark block not found')
activity = activity.replace(old_bookmarks, new_bookmarks, 1)

stats_start = activity.find('        statsHeader = Button(this).apply {')
stats_end_marker = '        root.addView(statsPanel, LinearLayout.LayoutParams(-1, -2).apply { setMargins(dp(12), 0, dp(12), dp(8)) })\n'
stats_end = activity.find(stats_end_marker, stats_start)
if stats_start < 0 or stats_end < 0:
    raise SystemExit('stats block not found')
stats_end += len(stats_end_marker)
new_stats = '''        val statsHeader = Button(this).apply {\n            text = "Куки  ▾"\n            setTextColor(text)\n            textSize = 14f\n            isAllCaps = false\n            gravity = Gravity.START or Gravity.CENTER_VERTICAL\n            background = rounded(panel, 16f, Color.rgb(37, 62, 51))\n            setPadding(dp(14), 0, dp(14), 0)\n            setOnClickListener { if (::statsController.isInitialized) statsController.toggle() }\n        }\n        root.addView(statsHeader, LinearLayout.LayoutParams(-1, dp(46)).apply { setMargins(dp(12), 0, dp(12), dp(6)) })\n\n        val statsPanel = card().apply {\n            visibility = View.GONE\n            orientation = LinearLayout.VERTICAL\n            setPadding(dp(12), dp(10), dp(12), dp(10))\n        }\n        val statsTop = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL; gravity = Gravity.CENTER_VERTICAL }\n        statsTop.addView(TextView(this).apply {\n            text = "Сессионные куки"\n            setTextColor(accent)\n            textSize = 12f\n            typeface = Typeface.DEFAULT_BOLD\n        }, LinearLayout.LayoutParams(0, -2, 1f))\n        statsTop.addView(compactButton("Копировать") { if (::statsController.isInitialized) statsController.copy() })\n        statsPanel.addView(statsTop)\n        val stats = TextView(this).apply {\n            setTextColor(text)\n            textSize = 12f\n            setTextIsSelectable(true)\n            setPadding(0, dp(8), 0, 0)\n        }\n        statsPanel.addView(stats)\n        root.addView(statsPanel, LinearLayout.LayoutParams(-1, -2).apply { setMargins(dp(12), 0, dp(12), dp(8)) })\n        statsController = WebCookieStatsController(\n            activity = this,\n            header = statsHeader,\n            panel = statsPanel,\n            textView = stats,\n            pageProvider = { if (::web.isInitialized) web.url ?: address.text?.toString().orEmpty() else address.text?.toString().orEmpty() }\n        )\n'''
activity = activity[:stats_start] + new_stats + activity[stats_end:]

activity = activity.replace('statsHandler.postDelayed({ if (::swipeRefresh.isInitialized) swipeRefresh.isRefreshing = false }, 15000)', 'uiHandler.postDelayed({ if (::swipeRefresh.isInitialized) swipeRefresh.isRefreshing = false }, 15000)')
activity = activity.replace('archive.clear(); if (::captureController.isInitialized) captureController.clearPending(); updateBadge(); updateStats()', 'archive.clear(); if (::captureController.isInitialized) captureController.clearPending(); updateBadge(); if (::statsController.isInitialized) statsController.update()')

ua_anchor = '        web.settings.userAgentString = userAgent\n'
if ua_anchor not in activity:
    raise SystemExit('user agent anchor not found')
activity = activity.replace(ua_anchor, ua_anchor + '        navigationController = WebNavigationController(this, web, address) { addRecord(it) }\n', 1)
activity = activity.replace('onSnapshot = { runOnUiThread { updateStats() } }', 'onSnapshot = { runOnUiThread { if (::statsController.isInitialized) statsController.update() } }')
activity = activity.replace('openInActiveWindow(request.url.toString()); temp.destroy(); return true', 'navigationController.openInActiveWindow(request.url.toString()); temp.destroy(); return true')
activity = activity.replace('if (url != "about:blank") { openInActiveWindow(url); temp.stopLoading(); temp.destroy() }', 'if (url != "about:blank") { navigationController.openInActiveWindow(url); temp.stopLoading(); temp.destroy() }')
activity = activity.replace('statsHandler.postDelayed({ captureController.ensureInstrumentation() }, 100)', 'uiHandler.postDelayed({ captureController.ensureInstrumentation() }, 100)')
activity = activity.replace('statsHandler.postDelayed({ captureController.ensureInstrumentation() }, 350)', 'uiHandler.postDelayed({ captureController.ensureInstrumentation() }, 350)')
activity = activity.replace('captureController.ensureInstrumentation(); captureController.captureLightPageSnapshot(); updateStats()', 'captureController.ensureInstrumentation(); captureController.captureLightPageSnapshot(); if (::statsController.isInitialized) statsController.update()')
activity = activity.replace('        navigate("https://evrasia.rest/")\n', '        navigationController.navigate("https://evrasia.rest/")\n', 1)

start = activity.find('    private fun toggleStats() {')
end = activity.find('    fun requestResourceCopy(url: String, headersJson: JSONObject?): Boolean =', start)
if start < 0 or end < 0:
    raise SystemExit('legacy ui helper block not found')
activity = activity[:start] + activity[end:]

activity = activity.replace('statsHandler.postDelayed({', 'uiHandler.postDelayed({')
activity = activity.replace('statsHandler.removeCallbacks', 'uiHandler.removeCallbacks')

old_lifecycle = '''    override fun onResume() {\n        super.onResume()\n        if (::statsPanel.isInitialized && statsPanel.visibility == View.VISIBLE) { statsHandler.removeCallbacks(statsTicker); statsHandler.post(statsTicker) }\n    }\n\n    override fun onPause() {\n        statsHandler.removeCallbacks(statsTicker)\n        super.onPause()\n    }\n\n    override fun onDestroy() {\n        statsHandler.removeCallbacks(statsTicker)\n        if (::captureController.isInitialized) captureController.shutdown()\n        super.onDestroy()\n    }\n'''
new_lifecycle = '''    override fun onResume() {\n        super.onResume()\n        if (::statsController.isInitialized) statsController.onResume()\n    }\n\n    override fun onPause() {\n        if (::statsController.isInitialized) statsController.onPause()\n        super.onPause()\n    }\n\n    override fun onDestroy() {\n        if (::statsController.isInitialized) statsController.destroy()\n        if (::captureController.isInitialized) captureController.shutdown()\n        super.onDestroy()\n    }\n'''
if old_lifecycle not in activity:
    raise SystemExit('lifecycle block not found')
activity = activity.replace(old_lifecycle, new_lifecycle, 1)

activity_path.write_text(activity)

Path('app/src/main/java/ru/evrasia/research/WebNavigationController.kt').write_text('''package ru.evrasia.research\n\nimport android.widget.EditText\nimport android.webkit.WebView\nimport androidx.appcompat.app.AppCompatActivity\nimport org.json.JSONObject\n\ninternal class WebNavigationController(\n    private val activity: AppCompatActivity,\n    private val web: WebView,\n    private val address: EditText,\n    private val record: (JSONObject) -> Unit\n) {\n    fun normalizeUrl(raw: String): String {\n        val value = raw.trim()\n        if (value.isBlank()) return "https://evrasia.rest/"\n        return if (value.startsWith("http://") || value.startsWith("https://")) value else "https://$value"\n    }\n\n    fun navigate(raw: String) {\n        val url = normalizeUrl(raw)\n        address.setText(url)\n        web.loadUrl(url)\n    }\n\n    fun openInActiveWindow(url: String) {\n        activity.runOnUiThread { navigate(url) }\n        record(JSONObject().put("source", "new-window").put("time", System.currentTimeMillis()).put("url", url).put("method", "GET"))\n    }\n}\n''')

Path('app/src/main/java/ru/evrasia/research/WebBookmarkController.kt').write_text('''package ru.evrasia.research\n\nimport android.content.Context\nimport android.widget.ArrayAdapter\nimport android.widget.Spinner\nimport android.widget.Toast\nimport androidx.appcompat.app.AppCompatActivity\n\ninternal class WebBookmarkController(\n    private val activity: AppCompatActivity,\n    private val normalizeUrl: (String) -> String,\n    private val onOpen: (String) -> Unit\n) {\n    private val bookmarks = mutableListOf<String>()\n    private lateinit var spinner: Spinner\n    private lateinit var adapter: ArrayAdapter<String>\n\n    fun bind(target: Spinner) {\n        spinner = target\n        adapter = ArrayAdapter(activity, android.R.layout.simple_spinner_dropdown_item, bookmarks)\n        spinner.adapter = adapter\n        load()\n    }\n\n    fun openSelected() {\n        if (bookmarks.isEmpty()) return\n        onOpen(bookmarks[spinner.selectedItemPosition])\n    }\n\n    fun save(raw: String) {\n        val url = normalizeUrl(raw)\n        if (!bookmarks.contains(url)) bookmarks.add(url)\n        bookmarks.sort()\n        adapter.notifyDataSetChanged()\n        persist()\n        spinner.setSelection(bookmarks.indexOf(url).coerceAtLeast(0))\n        Toast.makeText(activity, "Закладка сохранена", Toast.LENGTH_SHORT).show()\n    }\n\n    fun deleteSelected() {\n        if (bookmarks.isEmpty()) return\n        bookmarks.removeAt(spinner.selectedItemPosition)\n        adapter.notifyDataSetChanged()\n        persist()\n    }\n\n    private fun load() {\n        bookmarks.clear()\n        val saved = activity.getSharedPreferences("web-research", Context.MODE_PRIVATE).getStringSet("bookmarks", emptySet()) ?: emptySet()\n        bookmarks.addAll(saved.sorted())\n        adapter.notifyDataSetChanged()\n    }\n\n    private fun persist() {\n        activity.getSharedPreferences("web-research", Context.MODE_PRIVATE).edit().putStringSet("bookmarks", bookmarks.toSet()).apply()\n    }\n}\n''')

Path('app/src/main/java/ru/evrasia/research/WebCookieStatsController.kt').write_text('''package ru.evrasia.research\n\nimport android.content.ClipData\nimport android.content.ClipboardManager\nimport android.content.Context\nimport android.os.Handler\nimport android.os.Looper\nimport android.view.View\nimport android.webkit.CookieManager\nimport android.widget.Button\nimport android.widget.LinearLayout\nimport android.widget.TextView\nimport android.widget.Toast\nimport androidx.appcompat.app.AppCompatActivity\n\ninternal class WebCookieStatsController(\n    private val activity: AppCompatActivity,\n    private val header: Button,\n    private val panel: LinearLayout,\n    private val textView: TextView,\n    private val pageProvider: () -> String\n) {\n    private val handler = Handler(Looper.getMainLooper())\n    private val ticker = object : Runnable {\n        override fun run() {\n            if (panel.visibility == View.VISIBLE) {\n                update()\n                handler.postDelayed(this, 500)\n            }\n        }\n    }\n\n    fun toggle() {\n        val show = panel.visibility != View.VISIBLE\n        panel.visibility = if (show) View.VISIBLE else View.GONE\n        header.text = if (show) "Куки  ▴" else "Куки  ▾"\n        handler.removeCallbacks(ticker)\n        if (show) { update(); handler.post(ticker) }\n    }\n\n    fun copy() {\n        val manager = activity.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager\n        manager.setPrimaryClip(ClipData.newPlainText("web research statistics", textView.text ?: ""))\n        Toast.makeText(activity, "Статистика скопирована", Toast.LENGTH_SHORT).show()\n    }\n\n    fun update() {\n        val page = pageProvider()\n        val raw = CookieManager.getInstance().getCookie(page).orEmpty()\n        val cookies = raw.split(';').map { it.trim() }.filter { it.isNotBlank() }\n        textView.text = buildString {\n            append("Страница: ").append(page.ifBlank { "—" })\n            append("\\nКуки текущей сессии: ").append(cookies.size)\n            if (cookies.isNotEmpty()) {\n                append("\\n\\n")\n                cookies.forEachIndexed { i, c -> append(i + 1).append(". ").append(c).append('\\n') }\n            }\n        }.trimEnd()\n    }\n\n    fun onResume() {\n        if (panel.visibility == View.VISIBLE) { handler.removeCallbacks(ticker); handler.post(ticker) }\n    }\n\n    fun onPause() { handler.removeCallbacks(ticker) }\n    fun destroy() { handler.removeCallbacks(ticker) }\n}\n''')

print('stage10 refactor applied')
